# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e167941753bc2ac525535466032c0606526a995774ef06e0e58864fa3aeed89f43f4af02c2e891ebc6bf347dfd3dd536db2eef880a14ac6974ccdfc2207ecc5f

test:
  secret_key_base: 2039454c01f8c4bc4fc1e7cdbbf6d968581fd803c55bb5c8135e8c41264c4fa9ea1fd17300080685145a49dcffdf16515cd05c0981afc8ca33ddc72d8a725ebe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
